### ISSUE TITLE
Trying to use the UDA module and getting errors with source_type

### ISSUE THREAD

**Issue by amhaats1** [cohesity/ansible-collection#10]
## 🐛 Bug Report

Trying to use the module to register a DB2 source

## To Reproduce

(Write your steps here:)

I set **source_type: Linux**  - gets error
error_details": "b'{\\"errorCode\\":\\"KValidationError\\",\\"message\\":\\"validation failure list:\\\\\\\\nvalidation failure list:\\\\\\\\nvalidation failure list:\\\\\\\\nsourceType in body should be one of [kCockroachDB kDB2 kMySQL kOther kSapHana kSapMaxDB kSapOracle kSapSybase kSapSybaseIQ kSapASE kPostgreSQL]\\"}\\\\n'", "msg": "Unexpected error caused while managing the Cohesity Module."}

So then I set **source_type: kDB2** - gets error
"value of source_type must be one of: Linux, Windows, Aix, Solaris, SapHana, SapOracle, CockroachDB, MySQL, VMWareCDPFilter, PostgreSQL, got: kDB2"

Also tried **source_type: kOther** and receive an error 

## Expected behavior

 thought it would be able to register the DB2 source

(Write what you thought would happen.)

## Actual Behavior

 the script errored out and wouldn't continue

(Write what happened. Add screenshots, if applicable.)

**Comment by amhaats1** [comment]
Have you been able to look at this?

**Comment by naveena-maplelabs** [comment]
@amhaats1 what is the Cohesity cluster version you're using?

**Comment by amhaats1** [comment]
We are currently on 6.6.0d_u4 and will be upgrading to 6.6.0d_u5 this week.

**Comment by naveena-maplelabs** [comment]
@amhaats1 Can you please try providing source_type as DB2 instead of kDB2 and try once?

**Comment by naveena-maplelabs** [comment]
@amhaats1, These are list of source types currently supported.

1. Linux
2. Windows
3. Aix
4. Solaris
5. SapHana
6. SapOracle
7. CockroachDB
8. MySQL
9. VMWareCDPFilter
10. PostgreSQL

**Comment by amhaats1** [comment]
Is there a roadmap to be able to register DB2 sources using this module with the UDA adaptor.

**Comment by naveena-maplelabs** [comment]
We can add support for the same and add a patch release.

**Comment by naveena-maplelabs** [comment]
Fix added in our latest [release](https://galaxy.ansible.com/cohesity/dataprotect)

**Comment by amhaats1** [comment]
This fix still isn't working same errors when trying to use Source_type Linux  or DB2.  Same errors as above
