### ISSUE TITLE
This fix still isn't working same errors when trying to use Source_type Linux  or DB2.  Same errors as above

### ISSUE THREAD

**Issue by amhaats1** [cohesity/ansible-collection#11]
This fix still isn't working same errors when trying to use Source_type Linux  or DB2.  Same errors as in original issue

_Originally posted by @amhaats1 in https://github.com/cohesity/ansible-collection/issues/10#issuecomment-1281187556_

**Comment by amhaats1** [comment]
You are still missing the "DB2" option in your script

 type="str",
                choices=[
                    "Linux",
                    "Windows",
                    "Aix",
                    "Solaris",
                    "SapHana",
                    "SapOracle",
                    "CockroachDB",
                    "MySQL",
                    "VMWareCDPFilter",
                    "PostgreSQL",
                    "Other",

**Comment by naveena-maplelabs** [comment]
Can you try the following,
source_type: Other
os_type: DB2

**Comment by amhaats1** [comment]
Tried above suggestion, still errored,  Also tried source_type:Linux os_type:DB2
[job_79506.txt](https://github.com/cohesity/ansible-collection/files/9806278/job_79506.txt)
[job_79508.txt](https://github.com/cohesity/ansible-collection/files/9806279/job_79508.txt)

**Comment by naveena-maplelabs** [comment]
Thanks for testing. Added a fix here, https://galaxy.ansible.com/cohesity/dataprotect.

**Comment by amhaats1** [comment]
The correct setting to get this to work is 
source_type:Other
os_type:Linux
