### ISSUE TITLE
cohesity_uda_protection_group module throwing Exception errors

### ISSUE THREAD

**Issue by amhaats1** [cohesity/ansible-collection#12]
## 🐛 Bug Report

When using the cohesity_uda_protection_group module its throwing exception errors

File "/tmp/ansible_cohesity_uda_protection_group_payload_3ci7jls2/ansible_cohesity_uda_protection_group_payload.zip/ansible_collections/cohesity/dataprotect/plugins/modules/cohesity_uda_protection_group.py", line 429, in create_group
fatal: [localhost]: FAILED! => {
    "changed": false,
    "error_class": "Exception",
    "error_details": "Failed to create/update the protection group, err 'b'{\\"id\\":\\"147525775253105:1655914687332:189774\\",\\"name\\":\\"NP_UDB_lx14602_insttest_udbtest\\",\\"policyId\\":\\"147525775253105:1655914687332:114250\\",\\"storageDomainId\\":5,\\"description\\":\\"\\",\\"startTime\\":{\\"hour\\":16,\\"minute\\":0,\\"timeZone\\":\\"America/Los_Angeles\\"},\\"sla\\":[{\\"backupRunType\\":\\"kIncremental\\",\\"slaMinutes\\":60},{\\"backupRunType\\":\\"kFull\\",\\"slaMinutes\\":120}],\\"isActive\\":true,\\"isPaused\\":false,\\"environment\\":\\"kUDA\\",\\"permissions\\":null,\\"missingEntities\\":null,\\"udaParams\\":{\\"sourceId\\":6710,\\"objects\\":[{\\"name\\":\\"udbtest\\"}],\\"fullBackupArgs\\":\\"\\",\\"incrBackupArgs\\":\\"\\",\\"logBackupArgs\\":\\"--prune-logs-hours=1\\",\\"concurrency\\":1,\\"mounts\\":1}}\\\\n''",

## To Reproduce
Ansible Script Used
- hosts: localhost
  gather_facts: true
  collections:
    - cohesity.dataprotect
  tasks:
    - name: "Uda Create Protection job"
      cohesity_uda_protection_group:
        cluster: "labomaccohcls01"
        username: "username"
        password: "password"
        state: present
        protection_group_name: NP_UDB_lx14602_insttest_udbtest
        storage_domain: "DefaultStorageDomain"
        policy: "NP_UDB_24H_20M_14D"
        endpoint: "lx14602"      
        objects:
          - udbtest
        time_zone: America/Chicago
        start_time: "16:00"
        log_backup_args: "--prune-logs-hours=1"

## Expected behavior
To create the protection group without errors

## Actual Behavior

<!--
  Did something go wrong?   It created the Protection Group even with the exception errors
The full traceback is:
  File "/tmp/ansible_cohesity_uda_protection_group_payload_3ci7jls2/ansible_cohesity_uda_protection_group_payload.zip/ansible_collections/cohesity/dataprotect/plugins/modules/cohesity_uda_protection_group.py", line 429, in create_group
fatal: [localhost]: FAILED! => {
    "changed": false,
    "error_class": "Exception",
    "error_details": "Failed to create/update the protection group, err 'b'{\\"id\\":\\"147525775253105:1655914687332:189774\\",\\"name\\":\\"NP_UDB_lx14602_insttest_udbtest\\",\\"policyId\\":\\"147525775253105:1655914687332:114250\\",\\"storageDomainId\\":5,\\"description\\":\\"\\",\\"startTime\\":{\\"hour\\":16,\\"minute\\":0,\\"timeZone\\":\\"America/Los_Angeles\\"},\\"sla\\":[{\\"backupRunType\\":\\"kIncremental\\",\\"slaMinutes\\":60},{\\"backupRunType\\":\\"kFull\\",\\"slaMinutes\\":120}],\\"isActive\\":true,\\"isPaused\\":false,\\"environment\\":\\"kUDA\\",\\"permissions\\":null,\\"missingEntities\\":null,\\"udaParams\\":{\\"sourceId\\":6710,\\"objects\\":[{\\"name\\":\\"udbtest\\"}],\\"fullBackupArgs\\":\\"\\",\\"incrBackupArgs\\":\\"\\",\\"logBackupArgs\\":\\"--prune-logs-hours=1\\",\\"concurrency\\":1,\\"mounts\\":1}}\\\\n''",
    "invocation": {
        "module_args": {
            "cancel_active": false,
            "cluster": "labomaccohcls01",
            "concurrency": 1,
            "delete_backups": false,
            "description": "",
            "endpoint": "lx14602",
            "environment": "UDA",
            "full_backup_args": "",
            "incr_backup_args": "",
            "is_paused": true,
            "log_backup_args": "--prune-logs-hours=1",
            "mounts": 1,
            "name": "NP_UDB_lx14602_insttest_udbtest",
            "objects": [
                "udbtest"
            ],
            "ondemand_run_type": "Regular",
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "policy": "NP_UDB_24H_20M_14D",
            "protection_group_name": "NP_UDB_lx14602_insttest_udbtest",
            "protection_policy": "NP_UDB_24H_20M_14D",
            "start_time": "16:00",
            "state": "present",
            "storage_domain": "DefaultStorageDomain",
            "time_zone": "America/Chicago",
            "username": "ansible",
            "validate_certs": false
        }
    },
    "msg": "Unexpected error caused while managing the Cohesity Module."
}

Is something broken, or not behaving as you expected? The scripts shouldn't be throwing errors,  It created the Protection Group even with the errors but
it didn't set the correct timezone to America/Chicago, it used the default timezone America/LosAngeles 
Also it didn't create the job in a paused state like it should, which is the default

(Write what happened. Add screenshots, if applicable.)

**Comment by amhaats1** [comment]
The protection group was created in Cohesity but the timezone was incorrect and also didn't put the job on pause which is suppose to be the default if the parameter isn't set.

**Comment by naveena-maplelabs** [comment]
Hi @amhaats1,

Regarding **pauseJob** option issue, we'll add the fix in next release. Regarding the **timezone**, certain cluster version expects the time Zone field in name _timezone_ and some other versions under _timeZone_. Will check with the team internally and add fix if required.

Thanks for bringing this to our notice.

**Comment by amhaats1** [comment]
We are on 6.6.0d_u5_release-20220718_e181c2f1  
Looks like the API call uses timeZone
![APIcall_timeZone](https://user-images.githubusercontent.com/104401071/198035346-215410c1-77c4-4325-bb5b-274d1429f892.jpg)

**Comment by amhaats1** [comment]
The script is also missing any reference to using the alertPolicy and is defaulting to not having any alerts turned.  The default when using the Cohesity GUI is to have Alerts on Failure as the default.
![AlertPolicy](https://user-images.githubusercontent.com/104401071/198361702-3eab7180-e4ce-41f2-b061-bf8903128cbb.jpg)

**Comment by amhaats1** [comment]
Any update on this issue?

**Comment by naveena-maplelabs** [comment]
The timezone issue is fixed in recent release. Regarding the default alert policy, we currently dont support adding/updating alert policy through ansible collection, thanks

**Comment by naveena-maplelabs** [comment]
Can you try with latest release 1.1.0.

**Comment by naveena-maplelabs** [comment]
Please feel free to reopen if you face any issues
