### ISSUE TITLE
cohesity_oracle_source should not require database credentials due to OS authentication is an option

### ISSUE THREAD

**Issue by amhaats1** [cohesity/ansible-collection#20]
## 📚 Documentation

The documentation states a db username and password have to be specified but in the GUI
 if you want OS Authentication it doesn't require credentials
 
Module: cohesity_oracle_source

db_password:
    description:
      - "Specifies the password to access the target source database."
      - "This parameter will not be logged."
      - "Required when I(state=present)"
    type: str
  db_username:
    description:
      - "Specifies username to access the target source database."
      - "Required when I(state=present)"
    type: str

Please update documentation and notes in the module that db_password and db_username is not required.  I left these out and was still able to get the oracle source to register with OS Authentication which is what I was looking to do.
![Oracle_Source_registration](https://user-images.githubusercontent.com/104401071/223530360-5ef88db4-069a-435a-a4a4-dd6a0fda801b.jpg)

changed: [localhost] => (item=lx14845) => {
    "ansible_loop_var": "item",
    "changed": true,
    "invocation": {
        "module_args": {
            "cluster": "cluster",
            "db_password": "",
            "db_username": "",
            "endpoint": "lx14845",
            "force_register": true,
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "state": "present",
            "username": "ansible",
            "validate_certs": false
        }
    },
    "item": "lx14845",
    "msg": "Registration of Cohesity Protection Source Complete"
}

**Comment by naveena-maplelabs** [comment]
Sure @amhaats1 , will update thank you.

**Comment by naveena-maplelabs** [comment]
Please feel free to reopen if you face any issues

**Comment by amhaats1** [comment]
You updated only applicable when state is present but it shouldn't be required if the user is wanting to set the source as OS authentication instead of DB authentication.  
Example: which works to set the source as OS authentication
    - name: "Cohesity Protection Source: Register Oracle Source"
      cohesity_oracle_source:
        cluster: "omaccohcls00"
        username: "ansible"
        password: "cohesity123"
        validate_certs: "false"
        state: present
        endpoint: "{{ item }}"
        force_register: true

**Comment by naveena-maplelabs** [comment]
https://github.com/cohesity/ansible-collection/blob/main/docs/modules/cohesity_oracle_source.rst
It's optional parameter only.
`db_password (optional, str, None)`
`Specifies the password to access the target source database.`

`This parameter will not be logged.`

`Applicable only when state is set to present.`

`db_username (optional, str, None)`
`Specifies username to access the target source database.`

`Applicable only when state is set to present.`
