### ISSUE TITLE
cohesity_uda_source.py

### ISSUE THREAD

**Issue by amhaats1** [cohesity/ansible-collection#21]
## 🐛 Bug Report

We are trying to update a DB2 source that is already registered in the GUI as Source Type: DB2

Code:

        - name: Update Credentials for UDB source
          cohesity_uda_source:
              state: present
              cluster: "omaccohtestcls00.corp.mutualofomaha.com"
              username: "{{username}}"
              password: "{{password}}"
              validate_certs: false
              source_type: "DB2"
              os_type: "Linux"
              db_username: "{{dbusername}}"
              db_password: "{{newpassword}}"
              scripts_dir: "/opt/cohesity/db2/scripts"
              source_registration_args: "--source-name=lx14602_insttest_udbtest --db2profile-path=/data/insttest/sqllib/db2profile"
              hosts:
               - lx14602
              source_name: lx14602_insttest_udbtest
              endpoint: lx14602
              update_source: true
## Expected behavior
The credentials get updated with new password

## Actual Behavior
The ansible playbook failing due to it looking for DB2 as the source type
fatal: [localhost]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "cluster": "omaccohtestcls00.corp.mutualofomaha.com",
            "db_password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "db_username": "svcdpcbkup01",
            "endpoint": "lx14602",
            "hosts": [
                "lx14602"
            ],
            "mount_view": false,
            "os_type": "Linux",
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "scripts_dir": "/opt/cohesity/db2/scripts",
            "source_name": "lx14602_insttest_udbtest",
            "source_registration_args": "--source-name=lx14602_insttest_udbtest --db2profile-path=/data/insttest/sqllib/db2profile",
            "source_type": "DB2",
            "state": "present",
            "update_source": true,
            "username": "ansible",
            "validate_certs": false
        }
    },
    "msg": "value of source_type must be one of: Linux, Windows, Aix, Solaris, SapHana, SapOracle, CockroachDB, MySQL, VMWareCDPFilter, PostgreSQL, Other, got: DB2"

I tried to switch to source_type to  "Other" but got this 
error_details": "b'{\\"errorCode\\":\\"KInternalError\\",\\"message\\":\\"lx14602: Source type can\\\\'t be changed after registration. Old: kDB2 New: kOther.\\\\\\\\n\\"}\\\\n'" 

Can DB2 be added in the phython script as an option for source_type??

**Comment by naveena-maplelabs** [comment]
@amhaats1 Sure, we'll look into this, thank you for letting us know.

**Comment by amhaats1** [comment]
![UDB_currently_registered](https://user-images.githubusercontent.com/104401071/224039311-958f7e76-0805-49a9-9298-08a2c098c97d.jpg)

You might want to add all the options that are available in the in Cohesity 6.6 GUI these are the current selections we can choose from.
CockroachDB
DB2
PostgreSQL
SAP ASE
SAP Hana
SAP MaxDB
SAP Sybase IQ
MySQL
Other

**Comment by amhaats1** [comment]
Also the Default is Linux for source_type,  I would suggest taking out a default parameter, and just make the field required but not set a default.  Linux isn't a valid option in the gui for source_type

**Comment by naveena-maplelabs** [comment]
Thanks for the suggestion.

**Comment by naveena-maplelabs** [comment]
Updated the code, changes will be available in the next galaxy release.
