### ISSUE TITLE
Cohesity Refresh Protection Source

### ISSUE THREAD

**Issue by amhaats1** [cohesity/ansible-collection#22]
## 🚀 Feature Request

Refresh Cohesity registered Sources

Can we get a module that refreshes a source by putting in the name of the source?

Here is the API call that cohesity does to refresh a source

       url: https://{{ destination_host }}{{ refresh_path }}/{{sourceid}}
        method: POST
        validate_certs: no
        return_content: yes
        headers:
          Authorization: "Bearer {{ token.json.accessToken }}"
          accept: "application/json"
          Content-Type: "application/x-www-form-urlencoded"
        status_code: 204

I found some of the Python code might work.  Reference: https://github.com/bseltz-cohesity/scripts/blob/master/python/refreshSource/refreshSource.py

vip = args.vip
username = args.username
domain = args.domain
password = args.password
useApiKey = args.useApiKey
sourceNames = args.sourcename

# authenticate
apiauth(vip=vip, username=username, domain=domain, password=password, useApiKey=useApiKey)

if sourceNames is None:
    print('No sources specified')
    exit()

sources = api('get', 'protectionSources/registrationInfo?allUnderHierarchy=false')
if 'rootNodes' not in sources:
    print('No sources found')
    exit()

def getObjectId(sourcename):
    for source in sources['rootNodes']:
        if source['rootNode']['name'].lower() == sourcename.lower():
            return source['rootNode']['id']
    return None

for sourcename in sourceNames:
    objectId = getObjectId(sourcename)
    if objectId is not None:
        print('refreshing %s...' % sourcename)
        result = api('post', 'protectionSources/refresh/%s' % objectId)
    else:
        print('%s not found' % sourcename)

**Comment by naveena-maplelabs** [comment]
@amhaats1 Thanks for the suggestion, we'll look into this request. cc @pyashish

**Comment by naveena-maplelabs** [comment]
@amhaats1 We are adding support for source refresh, will let you now once its done. thanks

**Comment by naveena-maplelabs** [comment]
@amhaats1 Support for source refresh is  added in the latest [release](https://galaxy.ansible.com/cohesity/dataprotect). 
Please let us know if you have any questions

**Comment by amhaats1** [comment]
I’m having trouble trying to find what Ansible module I can use for source refresh’s, can someone point me to the documentation?

**Comment by amhaats1** [comment]
Can someone please point me where this reference is?

From: Michl, Angela
Sent: Tuesday, April 25, 2023 1:07 PM
To: cohesity/ansible-collection ***@***.***>; cohesity/ansible-collection ***@***.***>
Cc: Mention ***@***.***>
Subject: RE: [cohesity/ansible-collection] Cohesity Refresh Protection Source (Issue #22)

I’m having trouble trying to find what Ansible module I can use for source refresh’s, can someone point me to the documentation?

**Comment by amhaats1** [comment]
Where are the different refresh scripts located?
