### ISSUE TITLE
win agent install for 2019 servers

### ISSUE THREAD

**Issue by makstech7** [cohesity/ansible-collection#28]
## 🐛 Bug Report

I have basic ansible task for install win agent works fine on 2022 server but not in 2019 server

Task
      cohesity_win_agent:
        cluster: "{{ cohesity_server }}"
        username: "{{ cohesity_username }}"
        password: "{{ cohesity_password }}"
        validate_certs: false
        state: "{{ state | default('present') }}"
        preserve_settings: "{{ preserve_settings | default(False) }}"
        install_type: "{{ install_type | default('allcbt') }}"

error i get when i run for 2019 server

{
  "exception": "Cannot remove item C:\\Users\\winuser\\AppData\\Local\\Temp\\05169a79-4c19-4fa5-9da3-8cc2a904d9e8: The directory is not empty.\r\n\r\nAt line:247 char:7\r\n+       Remove-Item $tmpdir -Confirm:$False -Force -Recurse\r\n+       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\r\n    + CategoryInfo          : WriteError: (C:\\Users\\winuser....a3-8cc2a904d9e8:DirectoryInfo) [Remove-Item], IOException\r\n    + FullyQualifiedErrorId : RemoveFileSystemItemIOError,Microsoft.PowerShell.Commands.RemoveItemCommand\r\n\r\nScriptStackTrace:\r\nat Install-CohesityAgent, <No file>: line 247\r\nat <ScriptBlock>, <No file>: line 382\r\n\r\nSystem.IO.IOException: The directory is not empty.\r\n\r\n   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)\r\n   at System.IO.Directory.DeleteHelper(String fullPath, String userPath, Boolean recursive, Boolean throwOnTopLevelDirectoryNotFound, WIN32_FIND_DATA& data)\r\n   at System.IO.Directory.Delete(String fullPath, String userPath, Boolean recursive, Boolean checkHost)\r\n   at Microsoft.PowerShell.Commands.FileSystemProvider.RemoveFileSystemItem(FileSystemInfo fileSystemInfo, Boolean force)",
  "msg": "Unhandled exception while executing module: The directory is not empty.\r\n",
  "_ansible_no_log": null,
  "changed": false
}

**Comment by kavinagrawalcohesity** [comment]
@makstech7 It seems like the agent installation succeeded. Let us know if you are still facing the issue.
