### ISSUE TITLE
Can you add a feature to be able to update plugins/modules/cohesity_policy.py

### ISSUE THREAD

**Issue by amhaats1** [cohesity/ansible-collection#34]
## 🚀 Feature Request

Can you add a feature to be able to update a Protection Policy in script cohesity_policy.py? 
It currently only allows to create or delete the Protection Policy
## Example or reference 
I tried using state: 'present' and  add a Blackout Period but it doesn't allow for a update of the Protection Policy and comes back with the message the protection policy already exists.

Example - Update existing protection policy

- hosts: localhost
  gather_facts: true
  become: false

  collections:
    - cohesity.dataprotect

  tasks:

    - name: Update protection policy on cohesity server.
      cohesity_policy:
        cluster: "{{clustername}}"
        username: "{{ generic_username }}"
        password: "{{ generic_password }}"
        validate_certs: "false"
        name: "{{ policyname }}"
        state: 'present'
        blackout_window: 
          - blackout_period: "Tuesday;00:00;02:30"
        retries: 1
        retry_interval: 5
        days_to_retain: 14
        incremental_backup_schedule:
          periodicity: Daily

**Comment by amhaats1** [comment]
Any update on getting this corrected?

**Comment by naveena-maplelabs** [comment]
This feature is added in our new release. Please try with 1.1.9 version
