### ISSUE TITLE
Add support for NAS Protection Group

### ISSUE THREAD

**Issue by bab5470** [cohesity/ansible-collection#43]
## 🚀 Feature Request

As best as I can tell there doesn't seem to be a way to add a NAS protection group via the ansible module. We can create NAS sources but without a protection group, that's fairly useless. Please add support for NAS protection groups.

**Comment by naveena-maplelabs** [comment]
Please refer the playbook available [here](https://github.com/cohesity/ansible-collection/blob/main/playbooks/nas-workflow/create_nas_workflow.yml) for GenericNas protection group creation.

**Comment by ptp-sysadmin** [comment]
Thank you! I was expecting it to be called NAS Protection Policy.
