### ISSUE TITLE
Feature: Start/Stop sql protection jobs

### ISSUE THREAD

**Issue by MrEuds** [cohesity/ansible-collection#51]
## 🚀 Feature Request
Starting or stopping SQL protection jobs with the [cohesity_job](https://github.com/cohesity/ansible-collection/blob/main/plugins/modules/cohesity_job.py) module.
 
## Reference in [cohesity_job](https://github.com/cohesity/ansible-collection/blob/main/plugins/modules/cohesity_job.py)
Currently, the only supported environments types are list in the choices:
"VMware", "PhysicalFiles", "Physical", "GenericNas", "View"
 
For future enhancements, the below list should be consulted (like SQL).
 
## Example or reference
 
```
- name: Start sql backup job
  cohesity.dataprotect.cohesity_job:
    cluster: "{{ cluster }}"
    username: "{{ username }}"
    password: "{{ password }}"
    state: started/stopped
    name: sql_server
    environment: SQL
    ondemand_run_type: Regular
    include:
      - {{ db_name/db_id }}]

**Comment by darthVikes** [comment]
Same enhancement request, but also add "Oracle"  to the list as well. 

- name: Start sql backup job
  cohesity.dataprotect.cohesity_job:
    cluster: "{{ cluster }}"
    username: "{{ username }}"
    password: "{{ password }}"
    state: started/stopped
    name: Oracle
    environment: Oracle
    ondemand_run_type: Regular
    include:
      - {{ db_name/db_id }}]


Error when specifying Oracle as above.

fatal: [localhost]: FAILED! => {"changed": false, "msg": "value of environment must be one of: VMware, PhysicalFiles, Physical, GenericNas, View, got: Oracle"}


Is there a current workaround if its "Oracle" and I need to specify something different or will that also not work currently?

**Comment by kavinagrawalcohesity** [comment]
@MrEuds @darthVikes Kindly reach out to your accounts team to request for these features.
