### ISSUE TITLE
 NameError: name 'raise__cohesity_exception__handler' is not defined when Registering Cohesity Protection Source with Ansible

### ISSUE THREAD

**Issue by killerclaffey** [cohesity/ansible-collection#52]
## 🐛 Bug Report

When attempting to register a Cohesity Protection Source using the `cohesity.dataprotect.cohesity_source` module in Ansible ON Cohesity.DataProtect version 1.3.0, I encounter a `NameError: name 'raise__cohesity_exception__handler' is not defined` error. This issue occurs across multiple tasks that interact with the Cohesity modules.

## To Reproduce

1. Install the Cohesity agent on the target host.
2. Configure the Ansible environment with the necessary Cohesity modules. And PIP Requirements via the requirements.txt file
4. Run ANY 1 of the following Ansible playbook tasks:

```yaml
- name: Register Cohesity Protection Source
  cohesity.dataprotect.cohesity_source:
    cluster: "{{ cluster_addr }}"
    username: "admin"
    password: "{{ cohesity_password }}"
    endpoint: "{{ ansible_fqdn }}"
    environment: Physical
    host_type: Linux
    validate_certs: false
    force_register: true
    state: present
```

```yml
- name: Register Oracle Protection Source
  cohesity.dataprotect.cohesity_oracle_source:
    cluster: "{{ cluster_addr }}"
    username: "admin"
    password: "{{ cohesity_password }}"
    endpoint: "{{ ansible_fqdn }}"
    validate_certs: false
    state: present
```

```yml
- name: Configure Cohesity Protection Job
  cohesity.dataprotect.cohesity_job:
    cohesity_server: "{{ cluster_addr }}"
    username: "admin"
    password: "{{ cohesity_password }}"
    state: present
    validate_certs: false
    name: "AnsibleLinux1"
    environment: PhysicalFiles
    protection_sources:
      - endpoint: "{{ ansible_fqdn }}"
        paths:
          includeFilePath: "/"
          excludeFilePaths:
            - "/tmp"
            - "/var/log"
          skipNestedVolumes: true
    protection_policy: Bronze
    storage_domain: Default
```

ANY help or hints debugging this would be greatly appreciated!

## Expected behavior

The Cohesity Protection Source should be registered successfully without any errors. The protection job should be configured correctly.

## Actual Behavior

The playbook fails with the following error:

```plaintext
TASK [Register Cohesity Protection Source] **************************************************************************************************************************************
Wednesday 31 July 2024  15:14:20 -0400 (0:00:00.119)       0:00:06.602 ********
Wednesday 31 July 2024  15:14:20 -0400 (0:00:00.119)       0:00:06.602 ********
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: NameError: name 'raise__cohesity_exception__handler' is not defined
fatal: [local]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_cohesity.dataprotect.cohesity_source_payload_lq5rnlkl/ansible_cohesity.dataprotect.cohesity_source_payload.zip/ansible_collections/cohesity/dataprotect/plugins/module_utils/cohesity_hints.py\", line 86, in get_cohesity_client\nNameError: name 'CohesityClient' is not defined\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/root/.ansible/tmp/ansible-tmp-1722453260.0900724-13305-255485060524107/AnsiballZ_cohesity_source.py\", line 107, in <module>\n    _ansiballz_main()\n  File \"/root/.ansible/tmp/ansible-tmp-1722453260.0900724-13305-255485060524107/AnsiballZ_cohesity_source.py\", line 99, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/root/.ansible/tmp/ansible-tmp-1722453260.0900724-13305-255485060524107/AnsiballZ_cohesity_source.py\", line 48, in invoke_module\n    run_name='__main__', alter_sys=True)\n  File \"/usr/lib64/python3.6/runpy.py\", line 205, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib64/python3.6/runpy.py\", line 96, in _run_module_code\n    mod_name, mod_spec, pkg_name, script_name)\n  File \"/usr/lib64/python3.6/runpy.py\", line 85, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_cohesity.dataprotect.cohesity_source_payload_lq5rnlkl/ansible_cohesity.dataprotect.cohesity_source_payload.zip/ansible_collections/cohesity/dataprotect/plugins/modules/cohesity_source.py\", line 762, in <module>\n  File \"/tmp/ansible_cohesity.dataprotect.cohesity_source_payload_lq5rnlkl/ansible_cohesity.dataprotect.cohesity_source_payload.zip/ansible_collections/cohesity/dataprotect/plugins/modules/cohesity_source.py\", line 576, in main\n  File \"/tmp/ansible_cohesity.dataprotect.cohesity_source_payload_lq5rnlkl/ansible_cohesity.dataprotect.cohesity_source_payload.zip/ansible_collections/cohesity/dataprotect/plugins/module_utils/cohesity_hints.py\", line 91, in get_cohesity_client\nNameError: name 'raise__cohesity_exception__handler' is not defined\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: NameError: name 'raise__cohesity_exception__handler' is not defined
fatal: [server.domain.com]: FAILED! => {"changed": false, "module_stderr": "Shared connection to server.domain.com closed.\r\n", "module_stdout": "Traceback (most recent call last):\r\n  File \"/tmp/ansible_cohesity.dataprotect.cohesity_source_payload_rcgu3eik/ansible_cohesity.dataprotect.cohesity_source_payload.zip/ansible_collections/cohesity/dataprotect/plugins/module_utils/cohesity_hints.py\", line 86, in get_cohesity_client\r\nNameError: name 'CohesityClient' is not defined\r\n\r\nDuring handling of the above exception, another exception occurred:\r\n\r\nTraceback (most recent call last):\r\n  File \"/home/admin/.ansible/tmp/ansible-tmp-1722453260.2116103-13314-61563074983766/AnsiballZ_cohesity_source.py\", line 107, in <module>\r\n    _ansiballz_main()\r\n  File \"/home/admin/.ansible/tmp/ansible-tmp-1722453260.2116103-13314-61563074983766/AnsiballZ_cohesity_source.py\", line 99, in _ansiballz_main\r\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\r\n  File \"/home/admin/.ansible/tmp/ansible-tmp-1722453260.2116103-13314-61563074983766/AnsiballZ_cohesity_source.py\", line 48, in invoke_module\r\n    run_name='__main__', alter_sys=True)\r\n  File \"/usr/lib64/python3.6/runpy.py\", line 205, in run_module\r\n    return _run_module_code(code, init_globals, run_name, mod_spec)\r\n  File \"/usr/lib64/python3.6/runpy.py\", line 96, in _run_module_code\r\n    mod_name, mod_spec, pkg_name, script_name)\r\n  File \"/usr/lib64/python3.6/runpy.py\", line 85, in _run_code\r\n    exec(code, run_globals)\r\n  File \"/tmp/ansible_cohesity.dataprotect.cohesity_source_payload_rcgu3eik/ansible_cohesity.dataprotect.cohesity_source_payload.zip/ansible_collections/cohesity/dataprotect/plugins/modules/cohesity_source.py\", line 762, in <module>\r\n  File \"/tmp/ansible_cohesity.dataprotect.cohesity_source_payload_rcgu3eik/ansible_cohesity.dataprotect.cohesity_source_payload.zip/ansible_collections/cohesity/dataprotect/plugins/modules/cohesity_source.py\", line 576, in main\r\n  File \"/tmp/ansible_cohesity.dataprotect.cohesity_source_payload_rcgu3eik/ansible_cohesity.dataprotect.cohesity_source_payload.zip/ansible_collections/cohesity/dataprotect/plugins/module_utils/cohesity_hints.py\", line 91, in get_cohesity_client\r\nNameError: name 'raise__cohesity_exception__handler' is not defined\r\n", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}
```

## Additional Information

- **Python Version**: Python 3.11.9
- **Ansible Version**: 9.2.0
- **Cohesity Management SDK Version**: 1.10.1
- **Other Installed Packages**:
  - ansible-builder: 3.1.0
  - ansible-compat: 24.7.0
  - ansible-core: 2.16.9
  - ansible-lint: 24.7.0
  - ansible-navigator: 24.7.0
  - ansible-runner: 2.4.0
  - certifi: 2024.7.4
  - cohesity_management_sdk: 1.10.1
  - cryptography: 43.0.0
  - requests: 2.31.0
  - urllib3: 2.2.2

I am running this in a Python 3.11 virtual environment and using the contents of the Cohesity `requirements.txt` file to set up the environment. I am also following the standards outlined in the Cohesity inventory documentation.

---

**Comment by killerclaffey** [comment]
So im thinking this could be an incompatability in python 3.11

So i tried to downgrade to python 3.6

But when im running 3.6 i cannot install the correct version of requests or ansible
    ansible:   Downloading pywinrm-0.4.3-py2.py3-none-any.whl (44 kB)
    ansible: ERROR: Could not find a version that satisfies the requirement requests==2.31.0 (from versions: 0.2.0, 0.2.1, 0.2.2, 0.2.3, 0.2.4, 0.3.0, 0.3.1, 0.3.2, 0.3.3, 0.3.4, 0.4.0, 0.4.1, 0.5.0, 0.5.1, 0.6.0, 0.6.1, 0.6.2, 0.6.3, 0.6.4, 0.6.5, 0.6.6, 0.7.0, 0.7.1, 0.7.2, 0.7.3, 0.7.4, 0.7.5, 0.7.6, 0.8.0, 0.8.1, 0.8.2, 0.8.3, 0.8.4, 0.8.5, 0.8.6, 0.8.7, 0.8.8, 0.8.9, 0.9.0, 0.9.1, 0.9.2, 0.9.3, 0.10.0, 0.10.1, 0.10.2, 0.10.3, 0.10.4, 0.10.6, 0.10.7, 0.10.8, 0.11.1, 0.11.2, 0.12.0, 0.12.1, 0.13.0, 0.13.1, 0.13.2, 0.13.3, 0.13.4, 0.13.5, 0.13.6, 0.13.7, 0.13.8, 0.13.9, 0.14.0, 0.14.1, 0.14.2, 1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.0.4, 1.1.0, 1.2.0, 1.2.1, 1.2.2, 1.2.3, 2.0.0, 2.0.1, 2.1.0, 2.2.0, 2.2.1, 2.3.0, 2.4.0, 2.4.1, 2.4.2, 2.4.3, 2.5.0, 2.5.1, 2.5.2, 2.5.3, 2.6.0, 2.6.1, 2.6.2, 2.7.0, 2.8.0, 2.8.1, 2.9.0, 2.9.1, 2.9.2, 2.10.0, 2.11.0, 2.11.1, 2.12.0, 2.12.1, 2.12.2, 2.12.3, 2.12.4, 2.12.5, 2.13.0, 2.14.0, 2.14.1, 2.14.2, 2.15.1, 2.16.0, 2.16.1, 2.16.2, 2.16.3, 2.16.4, 2.16.5, 2.17.0, 2.17.1, 2.17.2, 2.17.3, 2.18.0, 2.18.1, 2.18.2, 2.18.3, 2.18.4, 2.19.0, 2.19.1, 2.20.0, 2.20.1, 2.21.0, 2.22.0, 2.23.0, 2.24.0, 2.25.0, 2.25.1, 2.26.0, 2.27.0, 2.27.1)
    
    (venv) [root@rclaffey-ansible-provisioner-h45g ~]# pip install ansible==9.2.0
ERROR: Could not find a version that satisfies the requirement ansible==9.2.0 (from versions: 1.0, 1.1, 1.2, 1.2.1, 1.2.2, 1.2.3, 1.3.0, 1.3.1, 1.3.2, 1.3.3, 1.3.4, 1.4, 1.4.1, 1.4.2, 1.4.3, 1.4.4, 1.4.5, 1.5, 1.5.1, 1.5.2, 1.5.3, 1.5.4, 1.5.5, 1.6, 1.6.1, 1.6.2, 1.6.3, 1.6.4, 1.6.5, 1.6.6, 1.6.7, 1.6.8, 1.6.9, 1.6.10, 1.7, 1.7.1, 1.7.2, 1.8, 1.8.1, 1.8.2, 1.8.3, 1.8.4, 1.9.0.1, 1.9.1, 1.9.2, 1.9.3, 1.9.4, 1.9.5, 1.9.6, 2.0.0.0, 2.0.0.1, 2.0.0.2, 2.0.1.0, 2.0.2.0, 2.1.0.0, 2.1.1.0, 2.1.2.0, 2.1.3.0, 2.1.4.0, 2.1.5.0, 2.1.6.0, 2.2.0.0, 2.2.1.0, 2.2.2.0, 2.2.3.0, 2.3.0.0, 2.3.1.0, 2.3.2.0, 2.3.3.0, 2.4.0.0, 2.4.1.0, 2.4.2.0, 2.4.3.0, 2.4.4.0, 2.4.5.0, 2.4.6.0, 2.5.0a1, 2.5.0b1, 2.5.0b2, 2.5.0rc1, 2.5.0rc2, 2.5.0rc3, 2.5.0, 2.5.1, 2.5.2, 2.5.3, 2.5.4, 2.5.5, 2.5.6, 2.5.7, 2.5.8, 2.5.9, 2.5.10, 2.5.11, 2.5.12, 2.5.13, 2.5.14, 2.5.15, 2.6.0a1, 2.6.0a2, 2.6.0rc1, 2.6.0rc2, 2.6.0rc3, 2.6.0rc4, 2.6.0rc5, 2.6.0, 2.6.1, 2.6.2, 2.6.3, 2.6.4, 2.6.5, 2.6.6, 2.6.7, 2.6.8, 2.6.9, 2.6.10, 2.6.11, 2.6.12, 2.6.13, 2.6.14, 2.6.15, 2.6.16, 2.6.17, 2.6.18, 2.6.19, 2.6.20, 2.7.0.dev0, 2.7.0a1, 2.7.0b1, 2.7.0rc1, 2.7.0rc2, 2.7.0rc3, 2.7.0rc4, 2.7.0, 2.7.1, 2.7.2, 2.7.3, 2.7.4, 2.7.5, 2.7.6, 2.7.7, 2.7.8, 2.7.9, 2.7.10, 2.7.11, 2.7.12, 2.7.13, 2.7.14, 2.7.15, 2.7.16, 2.7.17, 2.7.18, 2.8.0a1, 2.8.0b1, 2.8.0rc1, 2.8.0rc2, 2.8.0rc3, 2.8.0, 2.8.1, 2.8.2, 2.8.3, 2.8.4, 2.8.5, 2.8.6, 2.8.7, 2.8.8, 2.8.9, 2.8.10, 2.8.11, 2.8.12, 2.8.13, 2.8.14, 2.8.15, 2.8.16rc1, 2.8.16, 2.8.17rc1, 2.8.17, 2.8.18rc1, 2.8.18, 2.8.19rc1, 2.8.19, 2.8.20rc1, 2.8.20, 2.9.0b1, 2.9.0rc1, 2.9.0rc2, 2.9.0rc3, 2.9.0rc4, 2.9.0rc5, 2.9.0, 2.9.1, 2.9.2, 2.9.3, 2.9.4, 2.9.5, 2.9.6, 2.9.7, 2.9.8, 2.9.9, 2.9.10, 2.9.11, 2.9.12, 2.9.13, 2.9.14rc1, 2.9.14, 2.9.15rc1, 2.9.15, 2.9.16rc1, 2.9.16, 2.9.17rc1, 2.9.17, 2.9.18rc1, 2.9.18, 2.9.19rc1, 2.9.19, 2.9.20rc1, 2.9.20, 2.9.21rc1, 2.9.21, 2.9.22rc1, 2.9.22, 2.9.23rc1, 2.9.23, 2.9.24rc1, 2.9.24, 2.9.25rc1, 2.9.25, 2.9.26rc1, 2.9.26, 2.9.27rc1, 2.9.27, 2.10.0a1, 2.10.0a2, 2.10.0a3, 2.10.0a4, 2.10.0a5, 2.10.0a6, 2.10.0a7, 2.10.0a8, 2.10.0a9, 2.10.0b1, 2.10.0b2, 2.10.0rc1, 2.10.0, 2.10.1, 2.10.2, 2.10.3, 2.10.4, 2.10.5, 2.10.6, 2.10.7, 3.0.0b1, 3.0.0rc1, 3.0.0, 3.1.0, 3.2.0, 3.3.0, 3.4.0, 4.0.0a1, 4.0.0a2, 4.0.0a3, 4.0.0a4, 4.0.0b1, 4.0.0b2, 4.0.0rc1, 4.0.0, 4.1.0, 4.2.0, 4.3.0, 4.4.0, 4.5.0, 4.6.0, 4.7.0, 4.8.0, 4.9.0, 4.10.0, 5.0.0a1, 5.0.0a2, 5.0.0a3, 5.0.0b1, 5.0.0b2, 5.0.0rc1, 9.0.0a1, 9.0.0a2, 9.0.0a3, 9.0.0b1, 9.0.0rc1, 9.0.0)
ERROR: No matching distribution found for ansible==9.2.0



Can you please look at your listed requirements in the readme and the docs because on the version of python you have listed the requirements your asking for are not possible Im trying version 3.8 now will update after testing

**Comment by killerclaffey** [comment]
ansible 9.2.0 Requires-Python >=3.10

Trying 3.10 now....

**Comment by killerclaffey** [comment]
Can you please share what version of python you are using that is working?

**Comment by wayno123** [comment]
I'm having a similar error message while running the cohesity.dataprotect.cohesity_facts tasks. This is the simplest starting point to using Cohesity Dataprotect for major automation of a large financial institution vmware backup automation. Please help us to move this forward with your product.

`An exception occurred during task execution. To see the full traceback, use -vvv. The error was: NameError: name 'raise__cohesity_exception__handler' is not defined

fatal: [localhost]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_cohesity.dataprotect.cohesity_facts_payload_t4ycn8g5/ansible_cohesity.dataprotect.cohesity_facts_payload.zip/ansible_collections/cohesity/dataprotect/plugins/module_utils/cohesity_hints.py\", line 86, in get_cohesity_client\nNameError: name 'CohesityClient' is not defined\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/home/uxa/wc70-sa/.ansible/tmp/ansible-tmp-1726863979.6910055-3376193-186470408455680/AnsiballZ_cohesity_facts.py\", line 107, in <module>\n    _ansiballz_main()\n  File \"/home/uxa/wc70-sa/.ansible/tmp/ansible-tmp-1726863979.6910055-3376193-186470408455680/AnsiballZ_cohesity_facts.py\", line 99, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/uxa/wc70-sa/.ansible/tmp/ansible-tmp-1726863979.6910055-3376193-186470408455680/AnsiballZ_cohesity_facts.py\", line 47, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.cohesity.dataprotect.plugins.modules.cohesity_facts', init_globals=dict(_module_fqn='ansible_collections.cohesity.dataprotect.plugins.modules.cohesity_facts', _modlib_path=modlib_path),\n  File \"/usr/lib64/python3.9/runpy.py\", line 225, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib64/python3.9/runpy.py\", line 97, in _run_module_code\n    _run_code(code, mod_globals, init_globals,\n  File \"/usr/lib64/python3.9/runpy.py\", line 87, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_cohesity.dataprotect.cohesity_facts_payload_t4ycn8g5/ansible_cohesity.dataprotect.cohesity_facts_payload.zip/ansible_collections/cohesity/dataprotect/plugins/modules/cohesity_facts.py\", line 241, in <module>\n  File \"/tmp/ansible_cohesity.dataprotect.cohesity_facts_payload_t4ycn8g5/ansible_cohesity.dataprotect.cohesity_facts_payload.zip/ansible_collections/cohesity/dataprotect/plugins/modules/cohesity_facts.py\", line 166, in main\n  File \"/tmp/ansible_cohesity.dataprotect.cohesity_facts_payload_t4ycn8g5/ansible_cohesity.dataprotect.cohesity_facts_payload.zip/ansible_collections/cohesity/dataprotect/plugins/module_utils/cohesity_hints.py\", line 91, in get_cohesity_client\nNameError: name 'raise__cohesity_exception__handler' is not defined\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}`

**Comment by kavinagrawalcohesity** [comment]
> The playbook fails with the following error:
> 
> ```
> TASK [Register Cohesity Protection Source] **************************************************************************************************************************************
> Wednesday 31 July 2024  15:14:20 -0400 (0:00:00.119)       0:00:06.602 ********
> Wednesday 31 July 2024  15:14:20 -0400 (0:00:00.119)       0:00:06.602 ********
> An exception occurred during task execution. To see the full traceback, use -vvv. The error was: NameError: name 'raise__cohesity_exception__handler' is not defined
> fatal: [local]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_cohesity.dataprotect.cohesity_source_payload_lq5rnlkl/ansible_cohesity.dataprotect.cohesity_source_payload.zip/ansible_collections/cohesity/dataprotect/plugins/module_utils/cohesity_hints.py\", line 86, in get_cohesity_client\nNameError: name 'CohesityClient' is not defined\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/root/.ansible/tmp/ansible-tmp-1722453260.0900724-13305-255485060524107/AnsiballZ_cohesity_source.py\", line 107, in <module>\n    _ansiballz_main()\n  File \"/root/.ansible/tmp/ansible-tmp-1722453260.0900724-13305-255485060524107/AnsiballZ_cohesity_source.py\", line 99, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/root/.ansible/tmp/ansible-tmp-1722453260.0900724-13305-255485060524107/AnsiballZ_cohesity_source.py\", line 48, in invoke_module\n    run_name='__main__', alter_sys=True)\n  File \"/usr/lib64/python3.6/runpy.py\", line 205, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib64/python3.6/runpy.py\", line 96, in _run_module_code\n    mod_name, mod_spec, pkg_name, script_name)\n  File \"/usr/lib64/python3.6/runpy.py\", line 85, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_cohesity.dataprotect.cohesity_source_payload_lq5rnlkl/ansible_cohesity.dataprotect.cohesity_source_payload.zip/ansible_collections/cohesity/dataprotect/plugins/modules/cohesity_source.py\", line 762, in <module>\n  File \"/tmp/ansible_cohesity.dataprotect.cohesity_source_payload_lq5rnlkl/ansible_cohesity.dataprotect.cohesity_source_payload.zip/ansible_collections/cohesity/dataprotect/plugins/modules/cohesity_source.py\", line 576, in main\n  File \"/tmp/ansible_cohesity.dataprotect.cohesity_source_payload_lq5rnlkl/ansible_cohesity.dataprotect.cohesity_source_payload.zip/ansible_collections/cohesity/dataprotect/plugins/module_utils/cohesity_hints.py\", line 91, in get_cohesity_client\nNameError: name 'raise__cohesity_exception__handler' is not defined\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}
> An exception occurred during task execution. To see the full traceback, use -vvv. The error was: NameError: name 'raise__cohesity_exception__handler' is not defined
> fatal: [server.domain.com]: FAILED! => {"changed": false, "module_stderr": "Shared connection to server.domain.com closed.\r\n", "module_stdout": "Traceback (most recent call last):\r\n  File \"/tmp/ansible_cohesity.dataprotect.cohesity_source_payload_rcgu3eik/ansible_cohesity.dataprotect.cohesity_source_payload.zip/ansible_collections/cohesity/dataprotect/plugins/module_utils/cohesity_hints.py\", line 86, in get_cohesity_client\r\nNameError: name 'CohesityClient' is not defined\r\n\r\nDuring handling of the above exception, another exception occurred:\r\n\r\nTraceback (most recent call last):\r\n  File \"/home/admin/.ansible/tmp/ansible-tmp-1722453260.2116103-13314-61563074983766/AnsiballZ_cohesity_source.py\", line 107, in <module>\r\n    _ansiballz_main()\r\n  File \"/home/admin/.ansible/tmp/ansible-tmp-1722453260.2116103-13314-61563074983766/AnsiballZ_cohesity_source.py\", line 99, in _ansiballz_main\r\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\r\n  File \"/home/admin/.ansible/tmp/ansible-tmp-1722453260.2116103-13314-61563074983766/AnsiballZ_cohesity_source.py\", line 48, in invoke_module\r\n    run_name='__main__', alter_sys=True)\r\n  File \"/usr/lib64/python3.6/runpy.py\", line 205, in run_module\r\n    return _run_module_code(code, init_globals, run_name, mod_spec)\r\n  File \"/usr/lib64/python3.6/runpy.py\", line 96, in _run_module_code\r\n    mod_name, mod_spec, pkg_name, script_name)\r\n  File \"/usr/lib64/python3.6/runpy.py\", line 85, in _run_code\r\n    exec(code, run_globals)\r\n  File \"/tmp/ansible_cohesity.dataprotect.cohesity_source_payload_rcgu3eik/ansible_cohesity.dataprotect.cohesity_source_payload.zip/ansible_collections/cohesity/dataprotect/plugins/modules/cohesity_source.py\", line 762, in <module>\r\n  File \"/tmp/ansible_cohesity.dataprotect.cohesity_source_payload_rcgu3eik/ansible_cohesity.dataprotect.cohesity_source_payload.zip/ansible_collections/cohesity/dataprotect/plugins/modules/cohesity_source.py\", line 576, in main\r\n  File \"/tmp/ansible_cohesity.dataprotect.cohesity_source_payload_rcgu3eik/ansible_cohesity.dataprotect.cohesity_source_payload.zip/ansible_collections/cohesity/dataprotect/plugins/module_utils/cohesity_hints.py\", line 91, in get_cohesity_client\r\nNameError: name 'raise__cohesity_exception__handler' is not defined\r\n", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}
> ```

@killerclaffey It seems you have installed the packages from requirements.txt in Python 3.11.9. However, the Ansible module is still using Python 3.6 (as indicated in the logs). Please ensure that the correct Python interpreter version is being used, and let me know if the issue persists.

@wayno123 Could you also verify that you are using the correct Python interpreter? The logs suggest that the Ansible module in your case is also running with Python 3.6.
