### ISSUE TITLE
cohesity_win_agent - Incorrect wildcard usage for Get-ItemProperty

### ISSUE THREAD

**Issue by DegerfeldtConsulting** [cohesity/ansible-collection#53]
According to the official documentation the parameter "LiteralPath" does not support wildcards

"Specifies the path to the current location of the property. The value of LiteralPath is used exactly as it is typed. No characters are interpreted as wildcards"

https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.management/get-itemproperty?view=powershell-5.1

This means that Get-CohesityAgent will always return a null value and the module will report every installation as a failure no matter the actual result since the script is attempting to find a registry key using a wildcard

https://github.com/cohesity/ansible-collection/blame/4ea8671e1cd102395da154c93504479787872bdb/plugins/modules/cohesity_win_agent.ps1#L117

**Comment by kavinagrawalcohesity** [comment]
Fixed in #57
