### ISSUE TITLE
force_register - what does it actually do?

### ISSUE THREAD

**Issue by lukurde** [cohesity/ansible-collection#60]
## 📚 Documentation

This is the current documentation for the `force_register`
| Parameter | Choices / Defaults | Comments |
| --- | --- | --- |
|force_register | boolean Choices: true false  ← | Enabling this option will force the registration of the Cohesity Protection Source.|

https://galaxy.ansible.com/ui/repo/published/cohesity/dataprotect/content/module/cohesity_source/

This description is useless. I know it'll force the registration. But what does it actually do? It's used by default in the example but the source registration works without it so why is it part of the example? Should it be used by default? If so - why? Does it force re-registration every time? Is it dangerous?

**Comment by shubhamkr-cohesity** [comment]
Say a physical server is registered on cluster A, and you are trying to re-register the same source on cluster B. 
In such scenarios, the registration would fail. Using force_register would allow you to force register the source.
